name: Robot Framework CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Setup Node.js (necessário para npx/playwright)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          rfbrowser init --yes  # inicializa o BrowserLibrary
          npx playwright install  # baixa os browsers necessários

      # Run Robot Framework tests
      - name: Run Robot Framework tests
        run: |
          robot --outputdir results \
                --report report.html \
                --log log.html \
                --output output.xml \
                --reporttitle "Relatório de Testes OrangeHRM" \
                --logtitle "Log de Testes OrangeHRM" \
                tests/

      # Upload results
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: |
            results/report.html
            results/log.html
            results/output.xml
