name: Robot Framework CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          rfbrowser init --skip-browsers
          npx playwright install

      - name: Run Robot Framework tests
        run: |
          robot --outputdir results \
                --report report.html \
                --log log.html \
                --output output.xml \
                --reporttitle "Relatório de Testes OrangeHRM" \
                --logtitle "Log de Testes OrangeHRM" \
                tests/

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: |
            results/report.html
            results/log.html
            results/output.xml
